author: Michel Anderson Lutz Teixeira
author_url: https://twitter.com/michel_lutz
github_url: https://github.com/micheltlutz/MLChat
root_url: https://micheltlutz.github.io/MLChat/
module: MLChat
output: docs
theme: fullwidth
xcodebuild_arguments: [-workspace, 'MLChat.xcworkspace', -scheme, 'MLChat-iOS']
