disabled_rules:
  - identifier_name
  - large_tuple
  - trailing_whitespace
  - type_body_length
  - cyclomatic_complexity
  - function_parameter_count

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

identifier_name:
  min_length: # only min_length
  error: 3 # only error
  excluded: # excluded via string array
    - id
    - i
    - ok
    - x
    - y
    - URL
    - GlobalAPIKey
    - yes
    - no

line_length:
  warning: 152
  error: 300
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ### works up until this config rule
  ignores_interpolated_strings: true

function_body_length:
  warning: 60
  error: 80

